### ISSUE TITLE
🚨 CRITICAL: NativeWind CSS Interop Race Condition Breaks Navigation in Expo Router Apps

### ISSUE THREAD

**Issue by SammyTBrains** [nativewind/nativewind#1536]
I just lost **48+ hours** to a bug that had nothing to do with what the error message said.

---

### ❗The Error:

> "Couldn't find a navigation context."

Everything pointed to React Navigation setup or `NavigationContainer` not being initialized — but that wasn’t the issue **at all**.

---

### 💥 The Actual Problem:

It turns out NativeWind’s **CSS interop layer** can cause a **race condition** when used with **Expo Router + React Navigation**.
Certain utility classes trigger runtime CSS parsing **during render**, which delays navigation context initialization — and **breaks your whole app** in the most misleading way possible.

---

### 🧪 Environment:

* Expo Router v5+
* NativeWind v4+
* React Navigation v6/7
* React Native (any version)

---

### 🔥 Classes That Break Things:

* `shadow-*` (e.g. `shadow-sm`, `shadow-md`)
* `opacity-*` (e.g. `opacity-50`, `opacity-70`)
* `bg-color/opacity` shorthand (e.g. `bg-white/15`)
* `text-color/opacity` shorthand (e.g. `text-white/80`)

These don’t throw errors on their own — they **silently** delay context availability. That’s what makes it brutal to catch.

---

### 🛠️ The Fix:

Ditch those specific classes and use inline styles instead.

#### ❌ Before (breaks nav):

```tsx
<TouchableOpacity className="shadow-sm opacity-50 bg-white/15">
```

#### ✅ After (works fine):

```tsx
<TouchableOpacity 
  style={{ 
    opacity: 0.5, 
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  }}
>
```

---

### 🎯 Why This Matters:

* The error message is **completely misleading**
* It’s **timing-based** — which means it works sometimes and fails randomly
* This could easily waste **days** for any dev using NativeWind with Expo Router

---

### 🧵 Suggested Actions:

* [ ] Add a warning to NativeWind docs about this interop issue
* [ ] Possibly defer certain runtime class resolutions or provide config options
* [ ] Improve error context in React Navigation if feasible

---

### 🙏 Please Prioritize This

This issue hits core navigation and will keep biting unsuspecting devs.
If you’re using NativeWind + Expo Router and things suddenly stop working — **check your classNames** first before tearing your app apart.

---

**Thanks — and if anyone wants to verify or reproduce this, I’m happy to help. Just hoping no one else loses sleep over this like I did.**

**Comment by Sarah-okolo** [comment]
Unfortunately, I was the unsuspecting dev and lost days of sleep because of this. My whole app crashed completely, after working fine for days. Everything just failed silently. I had to run expo-doctor to give me a hint on what the issue was, and after hours of bite-sized tracing and creating new projects to test. Finally realized nativewind was the entire cause. Everything you stated in this issue is true; those classes are very unpredictable, and they might start off working for you, and all of a sudden, just decide they won't anymore. A very frustrating situation indeed.

**Comment by SammyTBrains** [comment]
Yess!!!
I really hope nativewind sees this as a very high priority

**Comment by marklawlor** [comment]
We will not investigate issues unless the submitter provides a reproduction repro. As described, it the issue doesn't make enough technical sense to me - so I need a reproduction to demonstrate the issue so I can pinpoint the problem.

Without a reproduction repo we will not be taking this as a high priority, as it doesn't appear to be a widely reported issue.

**Comment by SammyTBrains** [comment]
Alright, gotcha 👍. Haven’t had the time yet, but I’ll try to put together a reproduction repo. It mainly comes down to certain NativeWind classes like shadow-sm taking too long for Expo Router.

**Comment by sdjg113** [comment]
https://github.com/expo/expo/issues/38191#issuecomment-3190857006    I can confirm this shadow class name is indeed breaking my app as well. It is impossible to explain why. It happens sometime and not every time.  

 "expo-router": "~5.1.4",
 "expo": "^53.0.20",

**Comment by danieloi** [comment]
Spent almost an entire workday on this issue too. So glad I stumbled upon this

**Comment by sdjg113** [comment]
> Spent almost an entire workday on this issue too. So glad I stumbled upon this

A className breaking the app is the very last thing I would expect.

**Comment by Sarah-okolo** [comment]
`text-pretty` is also something to avoid. It broke my app completely. I had to clone my project and do a lot of divide and conquer till I was able to trace the error to just that one line. Once I removed it, the app became fine. When I added it back, it broke again. I did this multiple times to confirm it was the culprit. Took me hours to figure this out. And with the error message being somewhat vague or outright misleading. Most times, we are only left with the divide and conquer option to trace the errors.

**Comment by marklawlor** [comment]
Guys I appreciate peoples commenting on this issue, but we have the issue template for a reason. When issues do occur it's typically a combination of a number of factors (for example specific package versions) that cause the problem.

Simply saying "this doesn't work" and not following the template will result in your issue never being addressed.

If you do have an issue, please create a new issue and provide a reproduction repro so we can address the problem.

Please remember that all development on this project is done by volunteers in their own personal time

**Comment by sdjg113** [comment]
Sorry -  I didn't mean to sound unappreciative. I understand this is volunteer work and I am grateful. 
The issue is intermittent, making reproduction very hard. 
https://github.com/nativewind/nativewind/issues/1522 seems similar.
I replace className everytime I see this error, just wanted this issue to remain open for other devs - a className breaking the app is the last thing you'd expect.

https://github.com/user-attachments/assets/fdf2c603-ae55-47ed-bad4-3026b1906e37

**Comment by SammyTBrains** [comment]
> Guys I appreciate peoples commenting on this issue, but we have the issue template for a reason. When issues do occur it's typically a combination of a number of factors (for example specific package versions) that cause the problem.
> 
> Simply saying "this doesn't work" and not following the template will result in your issue never being addressed.
> 
> If you do have an issue, please create a new issue and provide a reproduction repro so we can address the problem.
> 
> Please remember that all development on this project is done by volunteers in their own personal time

I am so happy that I have been able to help other developers with this post
Also I am so sorry I have been so busy, that is why I didn't create a repo

I’ve published a minimal Expo Router repo that triggers the navigation error when toggling NativeWind shadow classes and created a new issue: nativewind/nativewind#1711 

Repo: https://github.com/SammyTBrains/nativewind-shadow-switch

Steps:
1. Install deps
2. Start the app
3. On the home screen, toggle Phone/Email a few times (both buttons use shadow-sm), then tap “Go to next screen”.
4. Intermittently you’ll get: “Couldn’t find a navigation context”.
Notes:

Removing shadow-* (e.g., shadow-sm) and opacity shorthand (bg-white/30) makes the issue disappear.
Inline styles avoid the crash.
Related reports:

Similar Expo comment: [https://github.com/expo/expo/issues/38191#issuecomment-3129106823](https://github.com/expo/expo/issues/38191#issuecomment-3129106823)

**Comment by otang** [comment]
I'm experiencing the same bug

**Comment by AVapps** [comment]
Same problem here with Expo 54. Removing every shadow and opacity classes solved it. This should at least appear in the docs !

**Comment by SennaSanzo** [comment]
Any updates on this? Is this still the case with NW v5?

**Comment by ahunts** [comment]
### ✅ Reproduction Case: `shadow-sm` in Modal Component

I can confirm this issue is still occurring with NativeWind v4 and Expo Router. Here's a specific reproduction case:

**Environment:**
- Expo SDK 54
- React Native 0.81.5
- NativeWind v4
- Expo Router (latest)

**Reproduction Steps:**
1. Use `shadow-sm` class on a `TouchableOpacity` component inside a modal
2. Modal is rendered within an Expo Router screen
3. App crashes with: `"Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'?"`

**Specific Code That Breaks:**
```tsx
// components/inventory/UseItemModal.tsx
<TouchableOpacity
  className={`flex-1 py-sm px-md rounded-[10px] items-center ${
    trackingMode === 'exact' ? 'bg-surface shadow-sm' : ''
  }`}
  onPress={() => setTrackingMode('exact')}
>
```

**Error Location:**
```
ERROR  [Error: Couldn't find a navigation context...]
Code: UseItemModal.tsx
  172 |             <TouchableOpacity
Call Stack
  UseItemModal (components/inventory/UseItemModal.tsx:172:13)
  InventoryListScreen (app/inventory/index.tsx:382:9)
  RootLayout (app/_layout.tsx:86:9)
```

**Workaround:**
Replaced `shadow-sm` with inline styles:
```tsx
const shadowSm = {
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  elevation: 2,
} as const;

<TouchableOpacity
  className={`flex-1 py-sm px-md rounded-[10px] items-center ${
    trackingMode === 'exact' ? 'bg-surface' : ''
  }`}
  style={trackingMode === 'exact' ? shadowSm : undefined}
>
```

**Impact:**
- This is a critical issue that breaks core navigation functionality
- The error message is misleading (points to NavigationContainer setup)
- Happens consistently when `shadow-sm` is used in modals/components rendered via Expo Router

**Request:**
Please prioritize fixing this or at minimum add clear documentation warning developers about this limitation. The workaround works but defeats the purpose of using Tailwind utility classes.

**Comment by rudgal** [comment]
Facing similar issue as described above:

- appears with dynamic classNames (via string interpolation or helpers like clsx)
- affects at least shadow, ring, opacity related classes

### Environment:

- Expo SDK 54.0.31
- React Native 0.81.5
- NativeWind 4.2.1
- Expo Router 6.0.15

**Comment by leemcmullen** [comment]
@marklawlor I stumbled across this exact same issue today too. You requested a reproducible demo, which some people above have provided. So I was wondering if this issue is going to be picked up at any point soon?

**Comment by vanenshi** [comment]
@leemcmullen seems like the repo is dead, their last real update is 3mo old
