### ISSUE TITLE
Cannot find module 'react-native-worklets/plugin'

### ISSUE THREAD

**Issue by bbhxwl** [nativewind/nativewind#1580]
https://www.nativewind.dev/docs/getting-started/installation

```


 node_modules\expo-router\entry.js: [BABEL] D:\project\git\xiaoNuoJiaHuApp\node_modules\expo-router\entry.js: Cannot find module 'react-native-worklets/plugin'
Require stack:
- D:\project\git\xiaoNuoJiaHuApp\node_modules\@babel\core\lib\config\files\plugins.js
- D:\project\git\xiaoNuoJiaHuApp\node_modules\@babel\core\lib\config\files\index.js
- D:\project\git\xiaoNuoJiaHuApp\node_modules\@babel\core\lib\index.js
- D:\project\git\xiaoNuoJiaHuApp\node_modules\metro-transform-worker\src\index.js
- D:\project\git\xiaoNuoJiaHuApp\node_modules\react-native-css-interop\dist\metro\transformer.js
- D:\project\git\xiaoNuoJiaHuApp\node_modules\metro\src\DeltaBundler\Worker.flow.js
- D:\project\git\xiaoNuoJiaHuApp\node_modules\metro\src\DeltaBundler\Worker.js
- D:\project\git\xiaoNuoJiaHuApp\node_modules\jest-worker\build\workers\processChild.js

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.

```

<img width="2426" height="954" alt="Image" src="https://github.com/user-attachments/assets/d156da8b-199b-4534-85a5-4e055334e633" />

**Comment by ahkela21** [comment]
facing this issue too

**Comment by bbhxwl** [comment]
> facing this issue too

The project is a good project, but it's too difficult for me to use in this new project.

**Comment by AdonisLima** [comment]
@bbhxwl It seems to be the same error as https://github.com/nativewind/nativewind/issues/1574. Downgrading to "4.1.23" works for now

**Comment by MikeW305** [comment]
Based on the commit linked above it seems 4.2.1 introduced a dep that causes issues for those still on expo 53. 

Staying on 4.1.23 for now as I'm not ready to upgrade to expo 54

**Comment by bbhxwl** [comment]
> Based on the commit linked above it seems 4.2.1 introduced a dep that causes issues for those still on expo 53.
> 
> Staying on 4.1.23 for now as I'm not ready to upgrade to expo 54

Expo 54 can also make mistakes.

**Comment by arealesramirez** [comment]
I'm seeing the same issue.

I'm using:
```
...
    "expo": "~53.0.22",
    "nativewind": "^4.1.23",
    "react-native-gesture-handler": "~2.28.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "~5.6.0",
    "react-native-screens": "~4.11.1",
    "react-native-svg": "^15.12.1",
    "react-native-web": "^0.20.0",
    "react-native-webview": "13.13.5",
...
```

I decided to add `"react-native-worklets/plugin"` to the babel config
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      "nativewind/babel",
    ],
    plugins: ["react-native-worklets/plugin"],
  };
};
```
This leads to the build to work, but when running the app, it triggers a similar error (I noticed it doesn't show `[BABEL]`)

<img width="772" height="60" alt="Image" src="https://github.com/user-attachments/assets/da906aa4-144d-4150-86a0-85e2843b9574" />


For context, I'm doing
1. Uninstall the app from the emulator
2. 
```
npx expo prebuild --clean
npx expo run:android
```
3. When I open the Android emulator, that's when the error is shown

**Comment by arealesramirez** [comment]
When I try with this babel config

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      "nativewind/babel",
    ],
    plugins: ["react-native-reanimated/plugin"],
  };
};

```
Essentially, using `"react-native-reanimated/plugin"`  instead of `"react-native-worklets/plugin"`, the error I see is


<img width="974" height="171" alt="Image" src="https://github.com/user-attachments/assets/6624dfe3-3bac-42df-9e01-188eccc35f31" />

Which has the `[BABEL]` tag in the error log.

**Comment by arealesramirez** [comment]
I've been trying for the last 3 days to find a solution.

Things I'm avoiding so far:
Upgrading to Expo 54
Upgrading React Native Animated to version 4

Not sure what is triggering the issue at this point

**Comment by MikeW305** [comment]
> > Based on the commit linked above it seems 4.2.1 introduced a dep that causes issues for those still on expo 53.
> > Staying on 4.1.23 for now as I'm not ready to upgrade to expo 54
> 
> Expo 54 can also make mistakes.

True. I tested upgrading to Expo 54 and 4.2.1 does in fact work for me.

Seems the new version is just not backwards compatible. Just going to wait until I'm ready to upgrade

**Comment by bbhxwl** [comment]
> [@bbhxwl](https://github.com/bbhxwl) It seems to be the same error as [#1574](https://github.com/nativewind/nativewind/issues/1574). Downgrading to "4.1.23" works for now

npm install nativewind@~4.1.23 react-native-reanimated@~3.17.4 react-native-safe-area-context@5.4.0
npm install --dev tailwindcss@^3.4.17 prettier-plugin-tailwindcss@^0.5.11

**Comment by Levi-Luo736** [comment]
> > [@bbhxwl](https://github.com/bbhxwl)似乎与[#1574](https://github.com/nativewind/nativewind/issues/1574)错误相同。目前可以降级到“4.1.23”
> 
> npm 安装 nativewind@~4.1.23 react-native-reanimated@~3.17.4 react-native-safe-area-context@5.4.0 npm 安装 --dev tailwindcss@^3.4.17 prettier-plugin-tailwindcss@^0.5.11

exactly alike,
`"dependencies": {
    "expo": "^53.0.0",
    "expo-constants": "~17.1.7",
    "expo-linking": "~7.1.7",
    "expo-router": "~5.1.6",
    "expo-status-bar": "~2.2.3",
    "nativewind": "^4.1.23",
    "prettier-plugin-tailwindcss": "^0.5.14",
    "react": "19.0.0",
    "react-native": "0.79.5",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-worklets-core": "^1.6.2",
    "tailwindcss": "^3.4.17"
  },
  "private": true,
  "devDependencies": {
    "babel-preset-expo": "~13.0.0",
    "metro": "^0.82.0",
    "prettier-plugin-tailwindcss": "^0.5.11",
    "tailwindcss": "^3.4.17"
  }`
but 

<img width="1128" height="192" alt="Image" src="https://github.com/user-attachments/assets/fbceaea9-983d-4746-9bff-c0df32394671" />

**Comment by bbhxwl** [comment]
> > > [@bbhxwl](https://github.com/bbhxwl)似乎与[#1574](https://github.com/nativewind/nativewind/issues/1574)错误相同。目前可以降级到“4.1.23”
> > 
> > 
> > npm 安装 nativewind@~4.1.23 react-native-reanimated@~3.17.4 react-native-safe-area-context@5.4.0 npm 安装 --dev tailwindcss@^3.4.17 prettier-plugin-tailwindcss@^0.5.11
> 
> exactly alike, `"dependencies": { "expo": "^53.0.0", "expo-constants": "~17.1.7", "expo-linking": "~7.1.7", "expo-router": "~5.1.6", "expo-status-bar": "~2.2.3", "nativewind": "^4.1.23", "prettier-plugin-tailwindcss": "^0.5.14", "react": "19.0.0", "react-native": "0.79.5", "react-native-reanimated": "~3.17.4", "react-native-safe-area-context": "5.4.0", "react-native-screens": "~4.11.1", "react-native-worklets-core": "^1.6.2", "tailwindcss": "^3.4.17" }, "private": true, "devDependencies": { "babel-preset-expo": "~13.0.0", "metro": "^0.82.0", "prettier-plugin-tailwindcss": "^0.5.11", "tailwindcss": "^3.4.17" }` but
> 
> <img alt="Image" width="1128" height="192" src="https://private-user-images.githubusercontent.com/110337030/491364435-fbceaea9-983d-4746-9bff-c0df32394671.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgyNTAxNzcsIm5iZiI6MTc1ODI0OTg3NywicGF0aCI6Ii8xMTAzMzcwMzAvNDkxMzY0NDM1LWZiY2VhZWE5LTk4M2QtNDc0Ni05YmZmLWMwZGYzMjM5NDY3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxOVQwMjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmFjNjczODU0ZTExZDBlY2I1ZjVhZTY2ZTA0ZGMxMzNjZWZhMTJiYjA3YzQyODc0OWRmMWFhZGY0YWQwODlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b5inC3ohvfrXfelX52YnBhngyncqcA8HKCdQP8uC1js">


The following has solved my problem, and currently I can use it for testing.

expo sdk 53  +
npm install nativewind@~4.1.23 react-native-reanimated@~3.17.4 react-native-safe-area-context@5.4.0
npm install --dev tailwindcss@^3.4.17 prettier-plugin-tailwindcss@^0.5.11

**Comment by jovsz** [comment]
> > > > [@bbhxwl](https://github.com/bbhxwl)似乎与[#1574](https://github.com/nativewind/nativewind/issues/1574)错误相同。目前可以降级到“4.1.23”
> > > 
> > > 
> > > npm 安装 nativewind@~4.1.23 react-native-reanimated@~3.17.4 react-native-safe-area-context@5.4.0 npm 安装 --dev tailwindcss@^3.4.17 prettier-plugin-tailwindcss@^0.5.11
> > 
> > 
> > exactly alike, `"dependencies": { "expo": "^53.0.0", "expo-constants": "~17.1.7", "expo-linking": "~7.1.7", "expo-router": "~5.1.6", "expo-status-bar": "~2.2.3", "nativewind": "^4.1.23", "prettier-plugin-tailwindcss": "^0.5.14", "react": "19.0.0", "react-native": "0.79.5", "react-native-reanimated": "~3.17.4", "react-native-safe-area-context": "5.4.0", "react-native-screens": "~4.11.1", "react-native-worklets-core": "^1.6.2", "tailwindcss": "^3.4.17" }, "private": true, "devDependencies": { "babel-preset-expo": "~13.0.0", "metro": "^0.82.0", "prettier-plugin-tailwindcss": "^0.5.11", "tailwindcss": "^3.4.17" }` but
> > <img alt="Image" width="1128" height="192" src="https://private-user-images.githubusercontent.com/110337030/491364435-fbceaea9-983d-4746-9bff-c0df32394671.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgyNTAxNzcsIm5iZiI6MTc1ODI0OTg3NywicGF0aCI6Ii8xMTAzMzcwMzAvNDkxMzY0NDM1LWZiY2VhZWE5LTk4M2QtNDc0Ni05YmZmLWMwZGYzMjM5NDY3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxOVQwMjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmFjNjczODU0ZTExZDBlY2I1ZjVhZTY2ZTA0ZGMxMzNjZWZhMTJiYjA3YzQyODc0OWRmMWFhZGY0YWQwODlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b5inC3ohvfrXfelX52YnBhngyncqcA8HKCdQP8uC1js">
> 
> The following has solved my problem, and currently I can use it for testing.
> 
> expo sdk 53 + npm install nativewind@~4.1.23 react-native-reanimated@~3.17.4 react-native-safe-area-context@5.4.0 npm install --dev tailwindcss@^3.4.17 prettier-plugin-tailwindcss@^0.5.11

Ty, that worked for me!

**Comment by iKotti** [comment]
I'm experiencing the same issue.

**package.json:**

```
“expo”: “53.0.22”,
"nativewind": “^4.1.23”,
“react-native-reanimated”: “~3.17.4”,
“tailwindcss”: “^3.4.17”,
“react-native-safe-area-context”: “5.4.0”,
```

I didn't have it in my project, but after reading that the solution worked, I installed it:

`“prettier-plugin-tailwindcss”: “^0.5.14”,
`

**babel.config.js:**
```
plugins: [
      [“module-resolver”, {
        root: [“./”],
        alias: {
          “@”: “./”,
          “tailwind.config”: “./tailwind.config.js”
        }
      }],
      “react-native-reanimated/plugin”
    ]
```

When I try Preview Build, I get an error:
```
[EAGER_BUNDLE] Android Bundling failed 5506ms index.ts (1 module)
[EAGER_BUNDLE] SyntaxError: index.ts: [BABEL] /tmp/ikotti/eas-build-local-nodejs/696fe9a3-b059-493d-a08b-a4c739b5562d/build/payment-tracker-app/index.ts: Cannot find module 'react-native-worklets/plugin'
```


If Expo 54 is the definitive solution, I'll start working on upgrading to 54. Does anyone know of another solution? :(

**Comment by jonathans199** [comment]
Unfortunately, I tried even downgrading to Nativewind v2 but still lots of issues with Postcss asking for worklets/plugin. 

Finally, I had to strip out Nativewind from our app and use AI to help convert all Tailwind utilities to regular stylesheets, hopefully in the near future this package could be stable again ☹️

Then I'll try to migrate over to tailwind once more.

**Comment by AxelAV95** [comment]
I’m having the same issue as yesterday. I tried adding the plugin to the Babel config file, but it still doesn’t work. Would upgrading to Expo 54 be a reliable solution?

**Comment by iKotti** [comment]
> I’m having the same issue as yesterday. I tried adding the plugin to the Babel config file, but it still doesn’t work. Would upgrading to Expo 54 be a reliable solution?

> Unfortunately, I tried even downgrading to Nativewind v2 but still lots of issues with Postcss asking for worklets/plugin.
> 
> Finally, I had to strip out Nativewind from our app and use AI to help convert all Tailwind utilities to regular stylesheets, hopefully in the near future this package could be stable again ☹️
> 
> Then I'll try to migrate over to tailwind once more.

I found a solution, but I can't get a preview build. The app is up and running. At least it's a solution for now so I can continue developing. I haven't changed anything in the package versions.

**1)** I installed React Native Worklets

`npm install react-native-worklets`

>Version: “react-native-worklets”: “^0.5.1”,

**2)** In babel.config.js, I updated the last line that says `“react-native-reanimated/plugin”` to `“react-native-worklets/plugin”`. 

**3)** I deleted `“node_modules”`, `“package-lock.json”`, and `“android”` and reinstalled the packages with `npm install`. 

> (You can also delete the ios folder created by prebuild if it exists. I'm only developing for Android for now.)

**4)** I ran prebuild one last time.
` npx expo prebuild -p android --clean `

5) I started Eas Build (I'm getting the builds locally).
`eas build --platform android --local --profile preview --clear-cache`

This only resolved the issue of getting the app up and running.

I'm still getting errors during the build. There's a conflict because it's also inside the reanimated worklet.

```
tmp/.../react-native-worklets/android/build/generated/source/codegen/jni/./rnworklets.h:22:18: error: redefinition of ‘NativeWorkletsModuleSpecJSI’
   22 | class JSI_EXPORT NativeWorkletsModuleSpecJSI : public JavaTurboModule {
      |                  ^
/tmp/.../react-native-reanimated/android/build/generated/source/codegen/jni/./rnreanimated.h:30:18: note: previous definition is here
   30 | class JSI_EXPORT NativeWorkletsModuleSpecJSI : public JavaTurboModule {
      |                  ^


```

The issue stems from the react-native-css-interop package included in nativewind.
This package requires react-native-worklets/plugin to be installed in its own babel.js file. Perhaps we'll need to find a compatible nativewind version for a smooth build.

Even though I haven't done any development, I can no longer get a build. I guess those using 53 have been thrown out because of Expo 54 :D 

I also tried to switch to Expo 54, but many other questions started to arise. If I can't find a solution, I will have to switch to Expo 54 and try to resolve the issues that arise during the transition. For now, I prefer to wait.

I hope continuing development will help you with this solution for now. Hoping for a permanent solution...

**Comment by hugovasko** [comment]
Hi, if you are on expo sdk 53 and have this issue, then setting "nativewind" to "4.1.23" works, but you have to remove the caret "^", so not this - "^4.1.23", but this - "4.1.23", and then you also have to delete the package-lock.json and node_modules. Then run "npm cache clean --force", "npm install", and when you run "npx expo start -c" everything should be fine :)

**Comment by yinyanlei-joe** [comment]
> Hi, if you are on expo sdk 53 and have this issue, then setting "nativewind" to "4.1.23" works, but you have to remove the caret "^", so not this - "^4.1.23", but this - "4.1.23", and then you also have to delete the package-lock.json and node_modules. Then run "npm cache clean --force", "npm install", and when you run "npx expo start -c" everything should be fine :)

It worked well！！

**Comment by AxelAV95** [comment]
> Hi, if you are on expo sdk 53 and have this issue, then setting "nativewind" to "4.1.23" works, but you have to remove the caret "^", so not this - "^4.1.23", but this - "4.1.23", and then you also have to delete the package-lock.json and node_modules. Then run "npm cache clean --force", "npm install", and when you run "npx expo start -c" everything should be fine :)

Thank you, this worked for me!

**Comment by imrankhanpersonalai** [comment]
Fixed by:

<img width="211" height="103" alt="Image" src="https://github.com/user-attachments/assets/5763bd72-acbc-4a3d-a5b3-9a2b3233feba" />

**Comment by brunoJSX** [comment]
We faced the same issue and, after extensive research, I found this PR https://github.com/software-mansion/react-native-reanimated/pull/8227 that seems to provide a temporary fix. However, they plan to include the official fix in version 4.1.1 of Reanimated.

`
"dependencies": {
    "@expo-google-fonts/poppins": "^0.4.1",
    "@rn-primitives/label": "^1.2.0",
    "@rn-primitives/slot": "^1.2.0",
    "@rn-primitives/toggle": "^1.2.0",
    "@tanstack/react-query": "^5.89.0",
    "axios": "^1.12.2",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "expo": "~54.0.9",
    "expo-constants": "~18.0.9",
    "expo-font": "~14.0.8",
    "expo-linking": "~8.0.8",
    "expo-router": "~6.0.7",
    "expo-splash-screen": "~31.0.10",
    "expo-status-bar": "~3.0.8",
    "lucide-react-native": "^0.544.0",
    "nativewind": "4.1.23",
    "react": "19.1.0",
    "react-dom": "19.1.0",
    "react-native": "0.81.4",
    "react-native-reanimated": "~4.1.0",
    "react-native-safe-area-context": "5.6.1",
    "react-native-screens": "~4.16.0",
    "react-native-web": "^0.21.1",
    "tailwind-merge": "^3.3.1"
  },
  "devDependencies": {
    "@types/react": "~19.1.0",
    "prettier-plugin-tailwindcss": "^0.5.14",
    "tailwindcss": "^3.4.17",
    "typescript": "~5.9.2"
  },
`

**Comment by brunoJSX** [comment]
We applied the same fix, but then ran into an error that only occurred in specific browsers on a particular machine.

<img width="1573" height="324" alt="Image" src="https://github.com/user-attachments/assets/d6b623b7-ddd4-4a1b-a635-0773ec5fa5ac" />

After some digging, we found this solution: https://github.com/nativewind/nativewind/issues/1580#issuecomment-3315248251 which seems to address the issue. However, in our case, it didn’t work 😅.

That said, if anyone else is facing the same problem, this approach might be worth trying.

**Comment by dictionMasterPd** [comment]
i was experiencing this same issue, follow some of the fixes mention here, by downgrading to nativewind:4.1.23 app works fine, but my tailwindcss stop working  i have tried the troubleshooting measures mention on their docs, everything seem fine, clear cache, verityInstallation, confirm tailwindcss cli is working generate output,css but no of the tailwind classes are working  "dependencies": {
    "@expo-google-fonts/inter": "^0.2.3",
    "@expo/metro-runtime": "~5.0.4",
    "@expo/vector-icons": "^14.1.0",
    "@hookform/resolvers": "^3.10.0",
    "@react-native-async-storage/async-storage": "2.1.2",
    "@react-native-community/datetimepicker": "8.4.1",
    "@react-native-community/netinfo": "^11.4.1",
    "@react-native-community/slider": "4.5.6",
    "@react-native-picker/picker": "2.11.1",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/native": "^7.0.14",
    "@reduxjs/toolkit": "^2.7.0",
    "@tanstack/react-query": "^5.63.0",
    "autoprefixer": "^10.4.20",
    "axios": "^1.8.4",
    "expo": "53.0.22",
    "expo-audio": "~0.4.9",
    "expo-av": "~15.1.7",
    "expo-blur": "~14.1.5",
    "expo-clipboard": "~7.1.5",
    "expo-constants": "~17.1.7",
    "expo-dev-client": "~5.2.4",
    "expo-file-system": "~18.1.11",
    "expo-font": "~13.3.2",
    "expo-haptics": "~14.1.4",
    "expo-linking": "~7.1.7",
    "expo-router": "~5.1.6",
    "expo-screen-capture": "~7.2.0",
    "expo-sharing": "~13.1.5",
    "expo-speech": "~13.1.7",
    "expo-splash-screen": "~0.30.10",
    "expo-sqlite": "~15.2.14",
    "expo-status-bar": "~2.2.3",
    "expo-symbols": "~0.4.5",
    "expo-system-ui": "~5.0.11",
    "expo-updates": "~0.28.17",
    "expo-video": "~2.2.2",
    "expo-web-browser": "~14.2.0",
    "lodash": "^4.17.21",
    "lucide-react-native": "^0.525.0",
    "nativewind": "4.1.23",
    "postcss": "^8.4.49",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-native": "0.79.5",
    "react-native-circular-progress-indicator": "^4.4.2",
    "react-native-css-interop": "~0.0.23",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-otp-component": "^1.0.6",
    "react-native-otp-entry": "^1.8.2",
    "react-native-paper": "^5.13.0",
    "react-native-paystack-webview": "^5.0.1",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-svg": "15.11.2",
    "react-native-toast-message": "^2.3.0",
    "react-native-web": "^0.20.0",
    "react-native-webview": "13.13.5",
    "react-redux": "^9.2.0",
    "yup": "^1.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~19.0.10",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~53.0.10",
    "prettier-plugin-tailwindcss": "0.5.11",
    "react-test-renderer": "18.3.1",
    "tailwindcss": "3.4.17",
    "typescript": "~5.8.3"
  },

**Comment by Axmdstar** [comment]
> Hi, if you are on expo sdk 53 and have this issue, then setting "nativewind" to "4.1.23" works, but you have to remove the caret "^", so not this - "^4.1.23", but this - "4.1.23", and then you also have to delete the package-lock.json and node_modules. Then run "npm cache clean --force", "npm install", and when you run "npx expo start -c" everything should be fine :)

thank you that removed worklets errors, but now the nativewind styles is not working for me, just plain text, did i miss something

 "dependencies": {
    "@babel/runtime": "^7.27.6",
    "@djthoms/pretty-checkbox": "^3.1.0",
    "@expo/vector-icons": "^14.1.0",
    "@react-native-async-storage/async-storage": "2.1.2",
    "@react-native-community/blur": "^4.4.1",
    "@react-native-community/datetimepicker": "8.4.1",
    "@react-native-community/slider": "4.5.6",
    "@react-native-picker/picker": "2.11.1",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/drawer": "^7.1.1",
    "@react-navigation/native": "^7.0.14",
    "@react-navigation/stack": "^7.1.2",
    "@rn-primitives/checkbox": "^1.1.0",
    "@rn-primitives/dialog": "^1.1.0",
    "@rn-primitives/portal": "^1.1.0",
    "@rn-primitives/slot": "^1.1.0",
    "@rn-primitives/tabs": "^1.1.0",
    "@rn-primitives/types": "^1.1.0",
    "@supabase/supabase-js": "^2.48.1",
    "@tanstack/react-query": "^5.76.1",
    "@types/react-native-snap-carousel": "^3.8.11",
    "ajv": "^8.17.1",
    "ajv-keywords": "^5.1.0",
    "base64-arraybuffer": "^1.0.2",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "expo": "^53.0.23",
    "expo-blur": "~14.1.5",
    "expo-constants": "~17.1.7",
    "expo-dev-client": "~5.2.4",
    "expo-device": "~7.1.4",
    "expo-document-picker": "~13.1.6",
    "expo-font": "~13.3.2",
    "expo-haptics": "~14.1.4",
    "expo-image-picker": "~16.1.4",
    "expo-linear-gradient": "~14.1.5",
    "expo-linking": "~7.1.7",
    "expo-navigation-bar": "~4.2.7",
    "expo-notifications": "~0.31.4",
    "expo-router": "~5.1.7",
    "expo-splash-screen": "~0.30.10",
    "expo-status-bar": "~2.2.3",
    "expo-symbols": "~0.4.5",
    "expo-system-ui": "~5.0.10",
    "expo-vector-icons": "^10.0.1",
    "expo-web-browser": "~14.2.0",
    "ldrs": "^1.1.6",
    "moti": "^0.30.0",
    "nativewind": "4.1.23",
    "prettier-plugin-tailwindcss": "^0.5.14",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-icons": "^5.4.0",
    "react-native": "0.79.5",
    "react-native-checkbox": "^2.0.0",
    "react-native-css-interop": "^0.2.1",
    "react-native-element-dropdown": "^2.12.4",
    "react-native-elements": "^3.4.3",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-image-picker": "^8.1.0",
    "react-native-radio-buttons-group": "^3.1.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "^5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-svg": "15.11.2",
    "react-native-tailwindcss": "^1.1.11",
    "react-native-uuid": "^2.0.3",
    "react-native-vector-icons": "^10.2.0",
    "react-native-web": "^0.20.0",
    "react-native-webview": "13.13.5",
    "react-native-worklets": "0.5.1",
    "react-native-worklets-core": "1.6.2",
    "tailwind-merge": "^2.6.0",
    "tailwind-rn": "^4.2.0",
    "tailwindcss": "^3.4.17",
    "tailwindcss-animate": "^1.0.7",
    "uuid": "^11.1.0",
    "zustand": "^5.0.3"
  }

**Comment by amjadbouhouch** [comment]
@YellMinNaing-micro any luck ?

**Comment by amjadbouhouch** [comment]
> Fixed by:
> 
> <img alt="Image" width="211" height="103" src="https://private-user-images.githubusercontent.com/199649216/491956296-5763bd72-acbc-4a3d-a5b3-9a2b3233feba.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4NDU5MTIsIm5iZiI6MTc1ODg0NTYxMiwicGF0aCI6Ii8xOTk2NDkyMTYvNDkxOTU2Mjk2LTU3NjNiZDcyLWFjYmMtNGEzZC1hNWIzLTlhMmIzMjMzZmViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyNlQwMDEzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGI4ZjBiMTYwZDgzMmQ5NWRhZWU0MjQ2ODA4NDU3Yjg4NWMzY2QxYmYxMjI1YWUwZWY3NzVhMDQ3NDYyMGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PAUk_HxTPp4w0uqHFg-B8GZoIraq81hkV4TutRJXlRM">

This works for me !
thanks

**Comment by Levi-Luo736** [comment]
> 你好，如果你使用的是 expo sdk 53 并且遇到了这个问题，那么将“nativewind”设置为“4.1.23”是可行的，但你必须删除插入符号“^”，所以不是这个“^4.1.23”，而是这个“4.1.23”，然后你还必须删除 package-lock.json 和 node_modules。然后运行“npm cache clean --force”、“npm install”，再运行“npx expo start -c”就应该没问题了 :)

This is a good solution. I just noticed that the same issue also occurred in the official demo. The reason is that the default dependency version in the official version is set to "latest".

**Comment by patelajay745** [comment]
> Fixed by:
> 
> <img alt="Image" width="211" height="103" src="https://private-user-images.githubusercontent.com/199649216/491956296-5763bd72-acbc-4a3d-a5b3-9a2b3233feba.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkyODY1MDgsIm5iZiI6MTc1OTI4NjIwOCwicGF0aCI6Ii8xOTk2NDkyMTYvNDkxOTU2Mjk2LTU3NjNiZDcyLWFjYmMtNGEzZC1hNWIzLTlhMmIzMjMzZmViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAwMVQwMjM2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWQ1YjAwMzNhMTZiYjdkNWFiZTNkZjQ5N2JmODQ2MGQ3NGVjYzk5ZWQ4OWJhYjk0MDFlYTAwZWFlN2MzZmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UIRCn0YR_oVZU-0yz2H38eeuGgJenydscDkGuq7WVWs">

It worked for me ❤️

**Comment by roilanrodriguez55** [comment]
> > [@bbhxwl](https://github.com/bbhxwl) It seems to be the same error as [#1574](https://github.com/nativewind/nativewind/issues/1574). Downgrading to "4.1.23" works for now
> 
> npm install nativewind@~4.1.23 react-native-reanimated@~3.17.4 react-native-safe-area-context@5.4.0 npm install --dev tailwindcss@^3.4.17 prettier-plugin-tailwindcss@^0.5.11

This works for me

**Comment by mmanrus** [comment]
I resolve the issue by removing "react-native-reanimated/plugin",
```
    plugins: [
    'react-native-worklets/plugin', 
    ],
```
replacing with these instead
 'react-native-worklets/plugin', 
  it works for me

**Comment by patelajay745** [comment]
> 'react-native-worklets/plugin',

Perfect solution

**Comment by arazi47** [comment]
Any solution for those of us who are on SDK 54?

**Comment by jpsnow72** [comment]
> [@bbhxwl](https://github.com/bbhxwl) It seems to be the same error as [#1574](https://github.com/nativewind/nativewind/issues/1574). Downgrading to "4.1.23" works for now

Thanks, this worked for me!

**Comment by OsaroImarhiagbe** [comment]
I see so many solutions here, are any of them permanent solutions to this bug?

**Comment by danstepanov** [comment]
For those on SDK 54, you can look to the following templates for a working version of `react-native-worklets/plugin`

Expo SDK 54 + Nativewind v5
- `npx rn-new@next --nativewind` (add `--expo-router` if you'd like)

Expo SDK 54 + Nativewind v4.1
- `npx rn-new@latest --nativewind` (add `--expo-router` if you'd like)

**Comment by aleksvalushko** [comment]
as mentiond above, upgrade `expo to 54.0.0` and `react-native-reanimated to 4.1.3`, it works for me finally

**Comment by danstepanov** [comment]
closing this as resolved as of my last comment

**Comment by meysam7631** [comment]
I have the same error and I used this solution and it worked. 
https://github.com/nativewind/nativewind/issues/1580#issuecomment-3310271613

**Comment by renfuturistics** [comment]
what worked for me was adding this to babel.config.js
  plugins: ["react-native-reanimated/plugin"],
and then doing
 npm start -- --reset-cache. works on    "expo": "~54.0.13",

**Comment by foysalkazi11** [comment]
I have the same error and change dependencies solved the issue.

"expo": "^53.0.15",
"nativewind": "^4.2.1",
"react-native-reanimated": "~3.17.4",
"react-native-safe-area-context": "5.4.0",

 "devDependencies": {
    "prettier-plugin-tailwindcss": "^0.5.11",
    "tailwindcss": "^3.4.17",
    "typescript": "~5.8.3"
  },

**Comment by Sukomal07** [comment]
I got the same error. I try the solution mentioned here, but the issue still isn't fixed. Please help me


i am using expo: 53.0.23 

node_modules\expo-router\entry.js: [BABEL] D:\projects\skoub_app\node_modules\expo-router\entry.js: Cannot find module 'react-native-worklets/plugin'
Require stack:
- D:\projects\skoub_app\node_modules\@babel\core\lib\config\files\plugins.js
- D:\projects\skoub_app\node_modules\@babel\core\lib\config\files\index.js
- D:\projects\skoub_app\node_modules\@babel\core\lib\index.js
- D:\projects\skoub_app\node_modules\metro-transform-worker\src\index.js
- D:\projects\skoub_app\node_modules\react-native-css-interop\dist\metro\transformer.js
- D:\projects\skoub_app\node_modules\metro\src\DeltaBundler\Worker.flow.js
- D:\projects\skoub_app\node_modules\metro\src\DeltaBundler\Worker.js
- D:\projects\skoub_app\node_modules\jest-worker\build\workers\processChild.js

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.

**Comment by timhilehin** [comment]
Having the same issue, has anyone been able to find a workaround for expo 53?

**Comment by hugovasko** [comment]
> Having the same issue, has anyone been able to find a workaround for expo 53?

I think that the best solution is to migrate to expo 54

**Comment by Sukomal07** [comment]
> > Having the same issue, has anyone been able to find a workaround for expo 53?
> 
> I think that the best solution is to migrate to expo 54

I created a new project with latest expo packages and migrate all of my code and it got fixed. :)

**Comment by imrankhanpersonalai** [comment]
Upgrade to v54 and it should work. Before aware of other breaking changes e.g if you use FlastList, write unit tests etc.

**Comment by harikrish-s** [comment]
adding this to the babel.config.js worked for me:
plugins: ["react-native-reanimated/plugin"],

I'm on:
"expo": "~52.0.47",
"nativewind": "^4.1.23",
"react-native": "0.76.9",
"react-native-reanimated": "~3.16.1",

**Comment by sebastiantuyu** [comment]
Installing nativewind 4.1.23 on Expo 53 works !

Answer: https://github.com/software-mansion/react-native-reanimated/issues/8242#issuecomment-3301600452

**Comment by bbhxwl** [comment]
> Installing nativewind 4.1.23 on Expo 53 works !
> 
> Answer: [software-mansion/react-native-reanimated#8242 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/8242#issuecomment-3301600452)

I am currently creating a new project, expo 54， I want to install nativeWind v5, but it cannot run.

**Comment by addyuchiha** [comment]
> > [@bbhxwl](https://github.com/bbhxwl) It seems to be the same error as [#1574](https://github.com/nativewind/nativewind/issues/1574). Downgrading to "4.1.23" works for now
> 
> npm install nativewind@~4.1.23 react-native-reanimated@~3.17.4 react-native-safe-area-context@5.4.0 npm install --dev tailwindcss@^3.4.17 prettier-plugin-tailwindcss@^0.5.11

This is the Solution

**Comment by isantoshgyawali** [comment]
Recently I got similar issue and nativewind@~4.1.23 didn't worked for @expo/53 
what I did was I searched react-native-worklets/plugin inside node_modules and found this

module.exports = function () {
  return {
    plugins: [
      require("./dist/babel-plugin").default,
      [
        "@babel/plugin-transform-react-jsx",
        {
          runtime: "automatic",
          importSource: "react-native-css-interop",
        },
      ],
      // Use this plugin in reanimated 4 and later
       "react-native-worklets/plugin",
    ],
  };
};

and I commented out that react-native-worklets/plugin and that worked 
so I tried @foysalkazi11 version that is 
 "nativewind": "^4.2.1",

and on that version the same file is 

module.exports = function () {
  return {
    plugins: [
      require("./dist/babel-plugin").default,
      [
        "@babel/plugin-transform-react-jsx",
        {
          runtime: "automatic",
          importSource: "react-native-css-interop",
        },
      ],
      // Use this plugin in reanimated 4 and later
      // "react-native-worklets/plugin",
    ],
  };
};

so this should always work
so prefering  "nativewind": "^4.2.1" would be better I guess so

**Comment by chandukasam** [comment]
For anyone else encountering this issue, here's a workaround that resolved the problem for me. It involves creating a local mock module for `react-native-worklets` to satisfy the dependency requirement.

### Solution:

1.  **Create a mock module directory:**
    In your project's mobile directory (or the root of your project), create a new folder structure: `mock-modules/react-native-worklets`.

2.  **Add a `package.json` for the mock module:**
    Inside `mock-modules/react-native-worklets`, create a `package.json` file with the following content:

    ```json
    {
      "name": "react-native-worklets",
      "version": "1.0.0",
      "description": "Mock module for react-native-worklets",
      "main": "index.js"
    }
    ```

3.  **Create a mock `index.js`:**
    In the same directory, create an `index.js` file that exports an empty object:

    ```javascript
    module.exports = {};
    ```

4.  **Create a mock Babel `plugin.js`:**
    This is the key step to resolve the "Cannot find module" error. Create a `plugin.js` file in the same directory:

    ```javascript
    module.exports = function() {
      return { visitor: {} };
    };
    ```

5.  **Update your project's `package.json`:**
    Finally, point to your new mock module in your main `package.json` file by adding it to your `devDependencies`:

    ```json
    "devDependencies": {
      // ... other dependencies
      "react-native-worklets": "file:./mock-modules/react-native-worklets"
    }
    ```

6.  **Re-install dependencies:**
    Run `yarn install` or `npm install` to link the local module.

After these steps, the Metro bundler should be able to find the required plugin, and the build should proceed without errors. Hope this helps
