### ISSUE TITLE
Error running TailwindCSS CLI, please run the CLI manually to see the error

### ISSUE THREAD

**Issue by hamdoudhakem** [nativewind/nativewind#813]
Hello everybody!

So I'm making a RN project that implements Tailwind css using Native Wind, my project has been working perfectly until lately when I started getting this error : 
![image](https://github.com/marklawlor/nativewind/assets/90524568/e703918e-9479-4d05-91dc-9aea7e7c5c74)

When I did go to the Native Wind documentation, this is what I saw : 
![image (1)](https://github.com/marklawlor/nativewind/assets/90524568/7b22fb98-47b2-45fa-9a33-c4589e4fda71)

and I don't have the file generated in the cache (the "node_modules/.cache/nativewind/<input-css-filename>.<platform>.css" file) maybe that have something to do with the error.
So what should I do ?

**Comment by marklawlor** [comment]
You should follow the instructions and run `npx tailwindcss --input <input.css>` and report what the error is

**Comment by Ucekay** [comment]
I have the same problem. For me, it does not happen with netivewind4.0.13, but with any other version, I get the same problem as mentioned here.
I checked inside `node_modules/.cache/nativewind/`,  but `<input-css-filename>.<platform>.css` is not generated. On the other hand, when I run `npx tailwindcss --input <input.css>`, I get the expected CSS. As written in the Troubleshooting section of the nativewind document, I tried to verify the nativewind installation, but I only get the same error.

But I don't know how to reproduce this problem. There is a YouTube video showing Expo Examples' `with-router-tailwind`, and in that video there was no problem, but when I tried the example in the same way, I had the same problem. Is this a problem with my environment?

**Comment by MyNameIsHakem** [comment]
> You should follow the instructions and run `npx tailwindcss --input <input.css>` and report what the error is

I already did that but there was no problem with the result as far as I could see.

**Comment by JWesorick** [comment]
Having the same issue.

**Comment by JWesorick** [comment]
My issue was resolved with the solution in https://github.com/marklawlor/nativewind/issues/751

**Comment by feledori** [comment]
This has to do with your local folder structure. Nativewind does not escape blank spaces when using the cli so it fails to call it. Try removing the blank space in the folder which has your local-chat folder in it. Then it should work for now. I created a pull request which should solve this issue.

**Comment by benrbowers** [comment]
Having this issue and working version for me seems to be `4.0.14`

Literally the bare minimum version for me because this is the version `gap-x` starts working.

And lo and behold, there seems to be a commit that deals with the tailwind cli between 14 and 15. I tried passing 'npx tailwindcss' and 'yarn tailwindcss' to the cliCommand option in the metro.config, but nothing seems to work for version 4.0.15 and onward.

**Comment by benrbowers** [comment]
After changing to 4.0.15 but reverting https://github.com/marklawlor/nativewind/commit/6bb5648f0cd0cd045e2f6a29f96ed73469fd9d25, the problem still persists. Not really sure what the problem is a this point, but the solution remains to be to use `4.0.14`

**Comment by angelo-hub** [comment]
I'm still getting this

**Comment by benrbowers** [comment]
> After changing to 4.0.15 but reverting [6bb5648](https://github.com/marklawlor/nativewind/commit/6bb5648f0cd0cd045e2f6a29f96ed73469fd9d25), the problem still persists. Not really sure what the problem is at this point, but the solution remains to be to use `4.0.14`

My problem ended up being yarn v1. Upgraded to yarn v4 and node 20.12.2, and nativewind@4.0.36 now works without hanging at the Tailwind CLI part

**Comment by greatcat19** [comment]
if you copy this command and paste it to the script phase of xcode, you'll see the actual error

it should be something like
```
ios/tailwind.config.js not found
```

there should be a way to change the path resolve of this config file

**Comment by vasyaqwe** [comment]
For me, removing all whitespaces to the input file fixed the issue

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
